name: mp3cd
description: Mp3c Dart implementation.
version: 1.0.0
repository: https://github.com/tytydraco/mp3cd

environment:
  sdk: ^3.12.2

dependencies:
  args: ^2.7.0
  path: ^1.9.1

dev_dependencies:
  very_good_analysis: ^10.3.0

executables:
  mp3cd: